title: HPQCI
description: International Workshop on High Performance and Quantum Computing Integration (HPQCI) @ HDPC2024.
header: First International Workshop on High Performance and Quantum Computing Integration (2024)
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman