title: HPQCI
description: International Workshop on High Performance and Quantum Computing Integration (HPQCI) @ CF2026.
header: Second International Workshop on High Performance and Quantum Computing Integration (2026)
where: Catania, Sicily, Italy
when: May 19-21, 2026
show_downloads: false
download_url: https://github.com/HPQCI/HPQCI.github.io/raw/main/downloads/HPQCI.zip
google_analytics:
news: 
theme: jekyll-theme-cayman
