title: HPQCI
description: International Workshop on High Performance and Quantum Computing Integration (HPQCI) @ HDPC2024.
header: First International Workshop on High Performance and Quantum Computing Integration (2024)
where: University of Pisa, Pisa, Italy
when: June 3, 2024
show_downloads: false
google_analytics:
news: Registration Deadline May 27th, 2024 AoE
theme: jekyll-theme-cayman